import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { ThemeToggle } from "@/components/ThemeToggle";
const TOTAL_FORM_STEPS = 3;
// ─── Shared styles (mirrors ProfileForm exactly) ──────────────────────────────
const inputCls = "mt-1 w-full rounded border border-surface-light-border dark:border-surface-dark-border bg-surface-light dark:bg-surface-dark text-ink-light-strong dark:text-ink-dark-strong placeholder:text-ink-light-faint dark:placeholder:text-ink-dark-faint px-3 py-2 focus:outline-none focus:border-brand-red focus:ring-1 focus:ring-brand-red transition";
const labelCls = "text-sm font-medium text-ink-light-muted dark:text-ink-dark-muted";
// ─── Sub-components ───────────────────────────────────────────────────────────
function SectionCard({ title, children, }) {
    return (_jsxs("section", { className: "flex flex-col gap-4 bg-surface-light dark:bg-surface-dark-alt rounded-lg border border-surface-light-border dark:border-surface-dark-border p-4", children: [_jsx("h3", { className: "text-xs font-bold uppercase tracking-wide text-brand-gold-dark dark:text-brand-gold border-b border-brand-gold/40 pb-1", children: title }), children] }));
}
function YesNo({ label, value, onChange, }) {
    return (_jsxs("div", { className: "text-sm", children: [_jsx("p", { className: "text-ink-light-strong dark:text-ink-dark-strong mb-1.5", children: label }), _jsx("div", { className: "flex gap-1.5", children: [
                    { l: "Yes", v: true },
                    { l: "No", v: false },
                    { l: "—", v: null },
                ].map(({ l, v }) => {
                    const active = value === v;
                    return (_jsx("button", { type: "button", onClick: () => onChange(v), className: `px-3 py-1 rounded-full text-xs font-bold border transition ${active
                            ? "bg-brand-gold text-black border-brand-gold shadow-sm"
                            : "bg-surface-light dark:bg-surface-dark text-ink-light-muted dark:text-ink-dark-muted border-surface-light-border dark:border-surface-dark-border hover:border-brand-gold hover:text-brand-gold-dark dark:hover:text-brand-gold"}`, children: l }, l));
                }) })] }));
}
function ProgressBar({ step }) {
    if (step === 0)
        return null;
    const pct = Math.round((step / TOTAL_FORM_STEPS) * 100);
    return (_jsx("div", { className: "w-full h-1 bg-surface-light-border dark:bg-surface-dark-border rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-brand-red rounded-full transition-all duration-500 ease-out", style: { width: `${pct}%` } }) }));
}
function PageHeader({ step, stepLabel }) {
    return (_jsxs("header", { className: "bg-surface-light dark:bg-surface-dark-alt border-b-2 border-brand-gold px-4 py-3 shrink-0 space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("h1", { className: "font-bold text-brand-red dark:text-brand-red-light flex items-center gap-2 text-lg", children: [_jsx("span", { className: "inline-block w-2 h-5 bg-brand-gold rounded-sm" }), "ScholarPath"] }), _jsx(ThemeToggle, {})] }), step > 0 && (_jsxs(_Fragment, { children: [_jsx(ProgressBar, { step: step }), _jsx("p", { className: "text-xs text-ink-light-muted dark:text-ink-dark-muted", children: stepLabel })] }))] }));
}
function NavBar({ onBack, onNext, nextLabel = "Continue", showBack = true, }) {
    return (_jsxs("div", { className: "shrink-0 border-t border-surface-light-border dark:border-surface-dark-border bg-surface-light dark:bg-surface-dark-alt px-4 py-3 flex items-center gap-3", children: [showBack && onBack && (_jsx("button", { type: "button", onClick: onBack, className: "px-4 py-2 rounded text-sm font-semibold text-ink-light-muted dark:text-ink-dark-muted border border-surface-light-border dark:border-surface-dark-border hover:border-brand-red/40 hover:text-ink-light-strong dark:hover:text-ink-dark-strong transition", children: "Back" })), _jsx("button", { type: "button", onClick: onNext, className: "ml-auto px-5 py-2 rounded bg-brand-red text-white text-sm font-bold hover:bg-brand-red-dark transition shadow-sm", children: nextLabel })] }));
}
export function Onboarding({ onComplete }) {
    const [step, setStep] = useState(0);
    const [profile, setProfile] = useState({});
    const update = (key, val) => setProfile((p) => ({ ...p, [key]: val }));
    const next = () => setStep((s) => Math.min(s + 1, 3));
    const back = () => setStep((s) => Math.max(s - 1, 0));
    const finish = () => onComplete(profile);
    const Shell = ({ children }) => (_jsx("div", { className: "flex flex-col h-full bg-surface-light-alt dark:bg-surface-dark rounded-lg overflow-hidden border border-surface-light-border dark:border-surface-dark-border", children: children }));
    const ScrollArea = ({ children }) => (_jsx("div", { className: "flex-1 overflow-y-auto", children: _jsx("div", { className: "max-w-lg mx-auto w-full px-4 py-6 flex flex-col gap-4", children: children }) }));
    // ══ Step 0: Welcome ════════════════════════════════════════════════════════
    if (step === 0) {
        return (_jsxs(Shell, { children: [_jsx(PageHeader, { step: 0 }), _jsxs("div", { className: "flex-1 flex flex-col items-center justify-center px-6 py-8 gap-6 text-center", children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-20 h-20 rounded-full border-2 border-brand-gold bg-brand-gold/10 flex items-center justify-center", children: _jsxs("svg", { width: "36", height: "36", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "1.5", className: "text-brand-gold-dark dark:text-brand-gold", children: [_jsx("path", { d: "M12 2L2 7l10 5 10-5-10-5z" }), _jsx("path", { d: "M2 17l10 5 10-5" }), _jsx("path", { d: "M2 12l10 5 10-5" })] }) }), _jsx("span", { className: "absolute -bottom-1 -right-1 w-6 h-6 rounded-full bg-brand-red flex items-center justify-center", children: _jsx("svg", { width: "12", height: "12", viewBox: "0 0 24 24", fill: "none", stroke: "white", strokeWidth: "3", children: _jsx("polyline", { points: "20 6 9 17 4 12" }) }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h2", { className: "text-2xl font-bold text-ink-light-strong dark:text-ink-dark-strong", children: "Welcome to ScholarPath" }), _jsx("p", { className: "text-sm text-ink-light-muted dark:text-ink-dark-muted max-w-sm mx-auto leading-relaxed", children: "Your AI-powered scholarship navigator for Map\u00FAa University. Ask eligibility questions in plain language \u2014 get answers grounded in the official handbook with page citations." })] }), _jsx("div", { className: "flex flex-wrap gap-2 justify-center", children: [
                                "📖 Handbook-grounded answers",
                                "🔖 Page citations included",
                                "🎯 Personalized to your profile",
                            ].map((f) => (_jsx("span", { className: "text-xs px-3 py-1.5 rounded-full bg-surface-light dark:bg-surface-dark-alt border border-surface-light-border dark:border-surface-dark-border text-ink-light-muted dark:text-ink-dark-muted", children: f }, f))) }), _jsxs("div", { className: "w-full max-w-sm flex items-start gap-3 rounded-lg border border-brand-gold/40 bg-brand-gold/10 px-4 py-3 text-sm text-ink-light-strong dark:text-ink-dark-strong text-left", children: [_jsxs("svg", { className: "mt-0.5 shrink-0 text-brand-gold-dark dark:text-brand-gold", width: "15", height: "15", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("circle", { cx: "12", cy: "12", r: "10" }), _jsx("line", { x1: "12", y1: "8", x2: "12", y2: "12" }), _jsx("line", { x1: "12", y1: "16", x2: "12.01", y2: "16" })] }), _jsxs("p", { children: ["We'll ask a few quick questions about your academic and financial background so ScholarPath can give you more relevant answers.", " ", _jsx("strong", { className: "text-ink-light-strong dark:text-ink-dark-strong", children: "All data stays on your device." })] })] })] }), _jsxs("div", { className: "shrink-0 border-t border-surface-light-border dark:border-surface-dark-border bg-surface-light dark:bg-surface-dark-alt px-4 py-3 flex items-center justify-between", children: [_jsx("button", { type: "button", onClick: finish, className: "text-sm text-ink-light-muted dark:text-ink-dark-muted hover:text-ink-light-strong dark:hover:text-ink-dark-strong transition underline underline-offset-2", children: "Skip setup" }), _jsx("button", { type: "button", onClick: next, className: "px-5 py-2 rounded bg-brand-red text-white text-sm font-bold hover:bg-brand-red-dark transition shadow-sm", children: "Get started \u2192" })] })] }));
    }
    // ══ Step 1: Academic ═══════════════════════════════════════════════════════
    if (step === 1) {
        return (_jsxs(Shell, { children: [_jsx(PageHeader, { step: 1, stepLabel: "Step 1 of 3 \u2014 Academic Info" }), _jsxs(ScrollArea, { children: [_jsxs("div", { children: [_jsx("h2", { className: "text-base font-bold text-ink-light-strong dark:text-ink-dark-strong", children: "Academic Information" }), _jsx("p", { className: "text-sm text-ink-light-muted dark:text-ink-dark-muted mt-1", children: "Used to match GWA requirements and year-level eligibility." })] }), _jsxs(SectionCard, { title: "Academic Standing", children: [_jsxs("label", { className: "block", children: [_jsxs("span", { className: labelCls, children: ["GWA", " ", _jsx("span", { className: "font-normal opacity-70", children: "(1.00 = highest, 5.00 = lowest)" })] }), _jsx("input", { type: "number", step: "0.01", min: "1", max: "5", placeholder: "e.g. 1.75", value: profile.gwa ?? "", onChange: (e) => update("gwa", e.target.value ? Number(e.target.value) : null), className: inputCls })] }), _jsxs("label", { className: "block", children: [_jsx("span", { className: labelCls, children: "Year Level" }), _jsxs("select", { value: profile.year_level ?? "", onChange: (e) => update("year_level", e.target.value || null), className: inputCls, children: [_jsx("option", { value: "", children: "\u2014 Select \u2014" }), _jsx("option", { children: "Grade 11" }), _jsx("option", { children: "Grade 12" }), _jsx("option", { children: "1st Year" }), _jsx("option", { children: "2nd Year" }), _jsx("option", { children: "3rd Year" }), _jsx("option", { children: "4th Year" }), _jsx("option", { children: "5th Year" })] })] }), _jsxs("label", { className: "block", children: [_jsx("span", { className: labelCls, children: "Program / Course" }), _jsx("input", { type: "text", placeholder: "e.g. BS Computer Engineering", value: profile.program ?? "", onChange: (e) => update("program", e.target.value || null), className: inputCls })] })] }), _jsx(SectionCard, { title: "High School (for incoming freshmen)", children: _jsxs("label", { className: "block", children: [_jsx("span", { className: labelCls, children: "Honors received at graduation" }), _jsxs("select", { value: profile.hs_honors ?? "", onChange: (e) => update("hs_honors", e.target.value || null), className: inputCls, children: [_jsx("option", { value: "", children: "\u2014 Select \u2014" }), _jsx("option", { value: "highest", children: "With Highest Honors" }), _jsx("option", { value: "high", children: "With High Honors" }), _jsx("option", { value: "with_honor", children: "With Honors" }), _jsx("option", { value: "none", children: "None / Not applicable" })] })] }) })] }), _jsx(NavBar, { showBack: false, onNext: next })] }));
    }
    // ══ Step 2: Financial + Status ════════════════════════════════════════════
    if (step === 2) {
        return (_jsxs(Shell, { children: [_jsx(PageHeader, { step: 2, stepLabel: "Step 2 of 3 \u2014 Financial & Status" }), _jsxs(ScrollArea, { children: [_jsxs("div", { children: [_jsx("h2", { className: "text-base font-bold text-ink-light-strong dark:text-ink-dark-strong", children: "Financial & Background" }), _jsx("p", { className: "text-sm text-ink-light-muted dark:text-ink-dark-muted mt-1", children: "Many need-based scholarships have income thresholds. Your answers stay on this device only." })] }), _jsx(SectionCard, { title: "Financial", children: _jsxs("label", { className: "block", children: [_jsx("span", { className: labelCls, children: "Annual Family Income (PHP)" }), _jsx("input", { type: "number", placeholder: "e.g. 480000", value: profile.family_income ?? "", onChange: (e) => update("family_income", e.target.value ? Number(e.target.value) : null), className: inputCls }), _jsx("p", { className: "text-xs text-ink-light-muted dark:text-ink-dark-muted mt-1", children: "Gross household income for the year. Leave blank to skip." })] }) }), _jsxs(SectionCard, { title: "Background", children: [_jsx(YesNo, { label: "Filipino citizen", value: profile.is_filipino, onChange: (v) => update("is_filipino", v) }), _jsx(YesNo, { label: "Person with disability (PWD)", value: profile.is_pwd, onChange: (v) => update("is_pwd", v) }), _jsx(YesNo, { label: "Member of an indigenous community", value: profile.is_indigenous, onChange: (v) => update("is_indigenous", v) }), _jsx(YesNo, { label: "Athlete (NCAA-eligible or represents Map\u00FAa)", value: profile.is_athlete, onChange: (v) => update("is_athlete", v) })] })] }), _jsx(NavBar, { onBack: back, onNext: next })] }));
    }
    // ══ Step 3: Mapúa Relationships ═══════════════════════════════════════════
    return (_jsxs(Shell, { children: [_jsx(PageHeader, { step: 3, stepLabel: "Step 3 of 3 \u2014 Map\u00FAa Connections" }), _jsxs(ScrollArea, { children: [_jsxs("div", { children: [_jsx("h2", { className: "text-base font-bold text-ink-light-strong dark:text-ink-dark-strong", children: "Map\u00FAa Relationships" }), _jsx("p", { className: "text-sm text-ink-light-muted dark:text-ink-dark-muted mt-1", children: "Several institutional scholarships are reserved for students connected to the Map\u00FAa community." })] }), _jsxs(SectionCard, { title: "Family & Institutional Ties", children: [_jsx(YesNo, { label: "Direct family member is a Map\u00FAa alumnus", value: profile.is_alumni_relative, onChange: (v) => update("is_alumni_relative", v) }), _jsx(YesNo, { label: "Child of a Map\u00FAa faculty member", value: profile.is_faculty_child, onChange: (v) => update("is_faculty_child", v) }), _jsx(YesNo, { label: "Map\u00FAa employee or family of one", value: profile.is_employee_relative, onChange: (v) => update("is_employee_relative", v) }), _jsx(YesNo, { label: "Sibling currently enrolled at Map\u00FAa", value: profile.has_sibling_enrolled, onChange: (v) => update("has_sibling_enrolled", v) })] }), _jsxs("div", { className: "flex items-start gap-3 rounded-lg border border-brand-gold/40 bg-brand-gold/10 px-4 py-3 text-sm text-ink-light-strong dark:text-ink-dark-strong", children: [_jsxs("svg", { className: "mt-0.5 shrink-0 text-brand-gold-dark dark:text-brand-gold", width: "15", height: "15", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("circle", { cx: "12", cy: "12", r: "10" }), _jsx("line", { x1: "12", y1: "8", x2: "12", y2: "12" }), _jsx("line", { x1: "12", y1: "16", x2: "12.01", y2: "16" })] }), _jsx("p", { children: "Your profile will be shared across all your chats and can be updated anytime from the sidebar." })] })] }), _jsx(NavBar, { onBack: back, onNext: finish, nextLabel: "Start chatting \u2192" })] }));
}
